version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/discovery-server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/movie-info-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/ratings-data-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/movie-catalog-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
